import type { WeaponDef, WeaponFx } from "./weapons.js";

const RECOIL_SPAM: readonly [number, number][] = [
  [0.15, 0.12],
  [0.18, -0.14],
  [0.2, 0.16],
  [0.22, -0.12],
  [0.24, 0.18],
];

const RECOIL_KICK: readonly [number, number][] = [
  [2.4, 0.3],
  [2.8, -0.4],
  [3.0, 0.2],
];

const RECOIL_HEAVY: readonly [number, number][] = [
  [3.5, 0.5],
  [4.0, -0.6],
];

const RECOIL_MID: readonly [number, number][] = [
  [0.55, 0.1],
  [0.65, -0.15],
  [0.7, 0.12],
  [0.75, -0.1],
  [0.8, 0.18],
];

/** AK / SMG vertical climb. */
const RECOIL_AUTO: readonly [number, number][] = [
  [0.35, 0.05],
  [0.42, -0.08],
  [0.48, 0.1],
  [0.52, -0.06],
  [0.55, 0.12],
  [0.58, -0.1],
  [0.6, 0.08],
];

function fx(partial: WeaponFx): WeaponFx {
  return partial;
}

type GgPartial = Omit<
  WeaponDef,
  "id" | "name" | "adsSpreadMult" | "adsFov" | "adsSensMult" | "scopeStyle"
> &
  Partial<
    Pick<
      WeaponDef,
      | "adsSpreadMult"
      | "adsFov"
      | "adsSensMult"
      | "scopeStyle"
      | "maxRange"
      | "meleeCone"
      | "fx"
      | "viewmodel"
      | "semiAuto"
      | "fireStyle"
      | "burstCount"
      | "explosionRadius"
      | "projectile"
      | "onHit"
      | "onHitMs"
      | "animProfile"
      | "sfx"
      | "vmKickYaw"
      | "vmKickRoll"
      | "shellEject"
    >
  >;

function gg(id: string, name: string, partial: GgPartial): WeaponDef {
  return {
    id,
    name,
    adsSpreadMult: partial.adsSpreadMult ?? 0.4,
    adsFov: partial.adsFov ?? 58,
    adsSensMult: partial.adsSensMult ?? 0.75,
    scopeStyle: partial.scopeStyle ?? "iron",
    maxRange: partial.maxRange,
    meleeCone: partial.meleeCone,
    fx: partial.fx,
    viewmodel: partial.viewmodel,
    semiAuto: partial.semiAuto,
    fireStyle: partial.fireStyle,
    burstCount: partial.burstCount,
    explosionRadius: partial.explosionRadius,
    projectile: partial.projectile,
    onHit: partial.onHit,
    onHitMs: partial.onHitMs,
    animProfile: partial.animProfile,
    sfx: partial.sfx,
    vmKickYaw: partial.vmKickYaw,
    vmKickRoll: partial.vmKickRoll,
    shellEject: partial.shellEject,
    damage: partial.damage,
    headshotMultiplier: partial.headshotMultiplier,
    magSize: partial.magSize,
    reloadMs: partial.reloadMs,
    fireRate: partial.fireRate,
    pellets: partial.pellets,
    spreadDeg: partial.spreadDeg,
    recoilPattern: partial.recoilPattern,
  };
}

/** Resolve fire style for branching (meme guns set this explicitly). */
export function resolveFireStyle(weapon: WeaponDef): NonNullable<WeaponDef["fireStyle"]> {
  if (weapon.fireStyle) return weapon.fireStyle;
  if (weapon.meleeCone != null) return "melee";
  if (weapon.projectile === "rocket") return "rocket";
  if (weapon.explosionRadius != null && weapon.explosionRadius > 0) return "splash";
  if (weapon.pellets > 1) return "shotgun";
  if (weapon.semiAuto) return "semi";
  return "auto";
}

export function resolveAnimProfile(
  weapon: WeaponDef,
): NonNullable<WeaponDef["animProfile"]> {
  if (weapon.animProfile) return weapon.animProfile;
  const style = resolveFireStyle(weapon);
  if (style === "melee") return "slash";
  if (style === "splash" || style === "rocket") return "toss";
  if (style === "shotgun") return "pump";
  if (style === "burst") return "spin";
  if (style === "semi") return "punch";
  if ((weapon.fireRate ?? 0) >= 12) return "spray";
  return "kick";
}

/** Procedural meme gun helpers — no `viewmodel` → themed blocky mesh. */
const meme = {
  pea: () =>
    gg("gg_pea", "Pea Shooter", {
      fireStyle: "auto",
      animProfile: "spray",
      sfx: "pea",
      shellEject: true,
      vmKickYaw: 0.4,
      damage: 8,
      headshotMultiplier: 1.4,
      magSize: 80,
      reloadMs: 1200,
      fireRate: 18,
      pellets: 1,
      spreadDeg: 1.1,
      recoilPattern: RECOIL_SPAM,
      fx: fx({
        primary: 0x3a8f3a,
        accent: 0x76e056,
        tracer: 0x8dff6a,
        muzzle: 0xb6ff88,
        shape: "pistol",
        tracerStyle: "chunk",
        tracerLife: 0.13,
        kickScale: 0.45,
        fovKickScale: 0.35,
        flashScale: 0.55,
        impactScale: 0.65,
      }),
    }),
  chicken: () =>
    gg("gg_chicken", "Rubber Chicken", {
      fireStyle: "semi",
      animProfile: "punch",
      sfx: "chicken",
      semiAuto: true,
      vmKickRoll: 1.2,
      damage: 32,
      headshotMultiplier: 1.2,
      magSize: 8,
      reloadMs: 1600,
      fireRate: 2.4,
      pellets: 1,
      spreadDeg: 1.8,
      recoilPattern: RECOIL_KICK,
      fx: fx({
        primary: 0xe8b84a,
        accent: 0xc45c26,
        tracer: 0xffd27a,
        muzzle: 0xffaa44,
        shape: "weird",
        tracerStyle: "arc",
        tracerLife: 0.24,
        kickScale: 2.1,
        fovKickScale: 1.8,
        flashScale: 1.0,
        impactScale: 1.8,
      }),
    }),
  potato: () =>
    gg("gg_potato", "Potato Cannon", {
      fireStyle: "splash",
      animProfile: "toss",
      sfx: "rocket",
      semiAuto: true,
      explosionRadius: 3.2,
      damage: 68,
      headshotMultiplier: 1.25,
      magSize: 3,
      reloadMs: 2800,
      fireRate: 0.7,
      pellets: 1,
      spreadDeg: 0.5,
      recoilPattern: RECOIL_HEAVY,
      adsFov: 50,
      fx: fx({
        primary: 0x8b6914,
        accent: 0x5c4010,
        tracer: 0xd4a574,
        muzzle: 0xffcc88,
        shape: "cannon",
        tracerStyle: "chunk",
        tracerLife: 0.35,
        kickScale: 2.9,
        fovKickScale: 3.0,
        flashScale: 2.2,
        impactScale: 2.4,
      }),
    }),
  confetti: () =>
    gg("gg_confetti", "Confetti SMG", {
      fireStyle: "shotgun",
      animProfile: "spray",
      sfx: "smg",
      shellEject: true,
      vmKickYaw: 0.8,
      damage: 5,
      headshotMultiplier: 1.3,
      magSize: 48,
      reloadMs: 1900,
      fireRate: 15,
      pellets: 4,
      spreadDeg: 2.4,
      recoilPattern: RECOIL_SPAM,
      fx: fx({
        primary: 0xff4d8d,
        accent: 0x6c5ce7,
        tracer: 0xff9ff3,
        muzzle: 0xffeaa7,
        shape: "smg",
        tracerStyle: "dots",
        tracerLife: 0.14,
        kickScale: 0.6,
        fovKickScale: 0.5,
        flashScale: 1.25,
        impactScale: 1.0,
      }),
    }),
  bees: () =>
    gg("gg_bees", "Beehive Blaster", {
      fireStyle: "shotgun",
      animProfile: "pump",
      sfx: "shotty",
      semiAuto: true,
      damage: 6,
      headshotMultiplier: 1.25,
      magSize: 6,
      reloadMs: 2400,
      fireRate: 1.4,
      pellets: 14,
      spreadDeg: 4.5,
      maxRange: 55,
      recoilPattern: RECOIL_KICK,
      onHit: "shock",
      onHitMs: 180,
      fx: fx({
        primary: 0xf0c000,
        accent: 0x2d2d2d,
        tracer: 0xffe066,
        muzzle: 0xfff3bf,
        shape: "shotgun",
        tracerStyle: "dots",
        tracerLife: 0.18,
        kickScale: 1.9,
        fovKickScale: 1.75,
        flashScale: 1.7,
        impactScale: 1.35,
      }),
    }),
  noodle: () =>
    gg("gg_noodle", "Noodle Launcher", {
      fireStyle: "semi",
      animProfile: "toss",
      sfx: "wet",
      semiAuto: true,
      damage: 40,
      headshotMultiplier: 1.4,
      magSize: 8,
      reloadMs: 2100,
      fireRate: 1.8,
      pellets: 1,
      spreadDeg: 0.4,
      recoilPattern: RECOIL_MID,
      onHit: "slip",
      onHitMs: 900,
      scopeStyle: "optic",
      adsFov: 48,
      fx: fx({
        primary: 0xe67e22,
        accent: 0xf5cba7,
        tracer: 0xff9f43,
        muzzle: 0xffdab0,
        shape: "cannon",
        tracerStyle: "ribbon",
        tracerLife: 0.34,
        kickScale: 1.6,
        fovKickScale: 1.35,
        flashScale: 1.15,
        impactScale: 1.7,
      }),
    }),
  slap: () =>
    gg("gg_slap", "Tactical Slap", {
      fireStyle: "melee",
      animProfile: "slash",
      sfx: "slap",
      semiAuto: true,
      damage: 55,
      headshotMultiplier: 1.1,
      magSize: 1,
      reloadMs: 700,
      fireRate: 2.2,
      pellets: 1,
      spreadDeg: 0,
      recoilPattern: RECOIL_HEAVY,
      maxRange: 7,
      meleeCone: 0.42,
      fx: fx({
        primary: 0xf5d0c5,
        accent: 0xe8a598,
        tracer: 0xffe0d6,
        muzzle: 0xffffff,
        shape: "melee",
        tracerStyle: "slash",
        tracerLife: 0.18,
        kickScale: 3.0,
        fovKickScale: 2.5,
        flashScale: 0.15,
        impactScale: 2.6,
      }),
    }),
  bubble: () =>
    gg("gg_bubble", "Bubble Blaster", {
      fireStyle: "shotgun",
      animProfile: "kick",
      sfx: "wet",
      damage: 12,
      headshotMultiplier: 1.8,
      magSize: 20,
      reloadMs: 2000,
      fireRate: 5.5,
      pellets: 3,
      spreadDeg: 2.0,
      recoilPattern: RECOIL_MID,
      onHit: "slip",
      onHitMs: 700,
      fx: fx({
        primary: 0x74b9ff,
        accent: 0xa29bfe,
        tracer: 0x81ecec,
        muzzle: 0xdfe6e9,
        shape: "weird",
        tracerStyle: "bubble",
        tracerLife: 0.26,
        kickScale: 0.75,
        fovKickScale: 0.6,
        flashScale: 1.15,
        impactScale: 1.8,
      }),
    }),
  disco: () =>
    gg("gg_disco", "Disco Shotgun", {
      fireStyle: "shotgun",
      animProfile: "spin",
      sfx: "shotty",
      semiAuto: true,
      vmKickRoll: 1.6,
      damage: 8,
      headshotMultiplier: 1.35,
      magSize: 6,
      reloadMs: 2500,
      fireRate: 1.35,
      pellets: 10,
      spreadDeg: 3.2,
      recoilPattern: RECOIL_KICK,
      fx: fx({
        primary: 0x9b59b6,
        accent: 0x3498db,
        tracer: 0xe056fd,
        muzzle: 0xffffff,
        shape: "shotgun",
        tracerStyle: "dots",
        tracerLife: 0.16,
        kickScale: 2.0,
        fovKickScale: 1.85,
        flashScale: 2.0,
        impactScale: 1.45,
      }),
    }),
  spoon: () =>
    gg("gg_spoon", "Rail Bent Spoon", {
      fireStyle: "semi",
      animProfile: "bolt",
      sfx: "sniper",
      semiAuto: true,
      shellEject: true,
      damage: 75,
      headshotMultiplier: 2.4,
      magSize: 4,
      reloadMs: 2900,
      fireRate: 0.65,
      pellets: 1,
      spreadDeg: 0.01,
      recoilPattern: RECOIL_HEAVY,
      scopeStyle: "sniper",
      adsFov: 26,
      adsSensMult: 0.42,
      fx: fx({
        primary: 0xbdc3c7,
        accent: 0x7f8c8d,
        tracer: 0xecf0f1,
        muzzle: 0xffffff,
        shape: "sniper",
        tracerStyle: "beam",
        tracerLife: 0.36,
        kickScale: 3.2,
        fovKickScale: 3.0,
        flashScale: 1.6,
        impactScale: 2.0,
      }),
    }),
  soaker: () =>
    gg("gg_soaker", "Super Soaker", {
      fireStyle: "auto",
      animProfile: "spray",
      sfx: "wet",
      vmKickYaw: 0.5,
      damage: 9,
      headshotMultiplier: 1.3,
      magSize: 70,
      reloadMs: 2300,
      fireRate: 14,
      pellets: 2,
      spreadDeg: 0.9,
      recoilPattern: RECOIL_SPAM,
      onHit: "slip",
      onHitMs: 1100,
      fx: fx({
        primary: 0x00cec9,
        accent: 0x0984e3,
        tracer: 0x81ecec,
        muzzle: 0xdfe6e9,
        shape: "weird",
        tracerStyle: "thick",
        tracerLife: 0.12,
        kickScale: 0.5,
        fovKickScale: 0.45,
        flashScale: 1.0,
        impactScale: 1.2,
      }),
    }),
  accordion: () =>
    gg("gg_accordion", "Accordion Shotty", {
      fireStyle: "shotgun",
      animProfile: "pump",
      sfx: "shotty",
      semiAuto: true,
      damage: 8,
      headshotMultiplier: 1.3,
      magSize: 5,
      reloadMs: 2600,
      fireRate: 1.15,
      pellets: 11,
      spreadDeg: 5.5,
      maxRange: 28,
      recoilPattern: RECOIL_KICK,
      fx: fx({
        primary: 0xd35400,
        accent: 0xf5b041,
        tracer: 0xe67e22,
        muzzle: 0xfdebd0,
        shape: "shotgun",
        tracerStyle: "ribbon",
        tracerLife: 0.16,
        kickScale: 2.2,
        fovKickScale: 2.0,
        flashScale: 1.7,
        impactScale: 1.4,
      }),
    }),
  shrink: () =>
    gg("gg_shrink", "Shrink Ray", {
      fireStyle: "auto",
      animProfile: "kick",
      sfx: "zap",
      damage: 15,
      headshotMultiplier: 1.5,
      magSize: 18,
      reloadMs: 1900,
      fireRate: 4.5,
      pellets: 1,
      spreadDeg: 0.12,
      recoilPattern: RECOIL_MID,
      onHit: "shrink",
      onHitMs: 2800,
      fx: fx({
        primary: 0x55efc4,
        accent: 0x00b894,
        tracer: 0x81ecec,
        muzzle: 0xffffff,
        shape: "pistol",
        tracerStyle: "beam",
        tracerLife: 0.24,
        kickScale: 0.8,
        fovKickScale: 0.7,
        flashScale: 1.5,
        impactScale: 1.2,
      }),
    }),
  thunder: () =>
    gg("gg_thunder", "Pocket Thunder", {
      fireStyle: "splash",
      animProfile: "punch",
      sfx: "zap",
      semiAuto: true,
      explosionRadius: 2.8,
      damage: 52,
      headshotMultiplier: 1.5,
      magSize: 6,
      reloadMs: 2200,
      fireRate: 1.6,
      pellets: 1,
      spreadDeg: 0.15,
      recoilPattern: RECOIL_MID,
      onHit: "shock",
      onHitMs: 450,
      fx: fx({
        primary: 0xf1c40f,
        accent: 0x2c3e50,
        tracer: 0xffeaa7,
        muzzle: 0xffffff,
        shape: "pistol",
        tracerStyle: "zigzag",
        tracerLife: 0.28,
        kickScale: 1.7,
        fovKickScale: 1.55,
        flashScale: 2.3,
        impactScale: 1.9,
      }),
    }),
  flappy: () =>
    gg("gg_flappy", "Flappy Burst", {
      fireStyle: "burst",
      burstCount: 3,
      animProfile: "spin",
      sfx: "burst",
      semiAuto: true,
      shellEject: true,
      vmKickYaw: 0.9,
      damage: 11,
      headshotMultiplier: 1.4,
      magSize: 36,
      reloadMs: 1700,
      fireRate: 2.2,
      pellets: 1,
      spreadDeg: 1.4,
      recoilPattern: RECOIL_SPAM,
      fx: fx({
        primary: 0xe17055,
        accent: 0xd63031,
        tracer: 0xff7675,
        muzzle: 0xfab1a0,
        shape: "smg",
        tracerStyle: "ribbon",
        tracerLife: 0.14,
        kickScale: 0.7,
        fovKickScale: 0.6,
        flashScale: 1.05,
        impactScale: 0.95,
      }),
    }),
  hammer: () =>
    gg("gg_hammer", "Gravity Hammer", {
      fireStyle: "melee",
      animProfile: "slam",
      sfx: "heavy",
      semiAuto: true,
      damage: 58,
      headshotMultiplier: 1.15,
      magSize: 1,
      reloadMs: 2400,
      fireRate: 0.85,
      pellets: 1,
      spreadDeg: 0,
      recoilPattern: RECOIL_HEAVY,
      maxRange: 7,
      meleeCone: 0.48,
      explosionRadius: 4.5,
      onHit: "shock",
      onHitMs: 350,
      fx: fx({
        primary: 0x636e72,
        accent: 0x2d3436,
        tracer: 0xb2bec3,
        muzzle: 0xdfe6e9,
        shape: "melee",
        tracerStyle: "slash",
        tracerLife: 0.22,
        kickScale: 3.4,
        fovKickScale: 3.2,
        flashScale: 0.2,
        impactScale: 3.0,
      }),
    }),
  pointer: () =>
    gg("gg_pointer", "Laser Pointer of Doom", {
      fireStyle: "auto",
      animProfile: "kick",
      sfx: "zap",
      damage: 22,
      headshotMultiplier: 2.8,
      magSize: 16,
      reloadMs: 1800,
      fireRate: 4.2,
      pellets: 1,
      spreadDeg: 0,
      recoilPattern: RECOIL_MID,
      scopeStyle: "optic",
      adsFov: 38,
      fx: fx({
        primary: 0xff3838,
        accent: 0x2d3436,
        tracer: 0xff3838,
        muzzle: 0xff6b6b,
        shape: "pistol",
        tracerStyle: "beam",
        tracerLife: 0.32,
        kickScale: 0.4,
        fovKickScale: 0.35,
        flashScale: 0.5,
        impactScale: 1.0,
      }),
    }),
  bananaPeel: () =>
    gg("gg_banana_peel", "Banana Peel SMG", {
      fireStyle: "auto",
      animProfile: "spray",
      sfx: "smg",
      shellEject: true,
      vmKickYaw: 0.7,
      damage: 11,
      headshotMultiplier: 1.4,
      magSize: 50,
      reloadMs: 1600,
      fireRate: 13,
      pellets: 1,
      spreadDeg: 0.7,
      recoilPattern: RECOIL_SPAM,
      onHit: "slip",
      onHitMs: 1400,
      fx: fx({
        primary: 0xf1c40f,
        accent: 0xf39c12,
        tracer: 0xffeaa7,
        muzzle: 0xfdf6e3,
        shape: "smg",
        tracerStyle: "chunk",
        tracerLife: 0.12,
        kickScale: 0.7,
        fovKickScale: 0.55,
        flashScale: 1.05,
        impactScale: 1.15,
      }),
    }),
  ban: () =>
    gg("gg_ban", "Ban Hammer", {
      fireStyle: "melee",
      animProfile: "slam",
      sfx: "heavy",
      semiAuto: true,
      damage: 85,
      headshotMultiplier: 1.4,
      magSize: 2,
      reloadMs: 2600,
      fireRate: 1.0,
      pellets: 1,
      spreadDeg: 0,
      recoilPattern: RECOIL_HEAVY,
      maxRange: 9,
      meleeCone: 0.32,
      onHit: "freeze",
      onHitMs: 1200,
      fx: fx({
        primary: 0x2c3e50,
        accent: 0xe74c3c,
        tracer: 0xff6b6b,
        muzzle: 0xffabab,
        shape: "melee",
        tracerStyle: "slash",
        tracerLife: 0.24,
        kickScale: 3.1,
        fovKickScale: 2.9,
        flashScale: 0.25,
        impactScale: 2.8,
      }),
    }),
  golden: () =>
    gg("gg_golden", "Golden Banana", {
      fireStyle: "semi",
      animProfile: "punch",
      sfx: "zap",
      semiAuto: true,
      damage: 100,
      headshotMultiplier: 2.2,
      magSize: 1,
      reloadMs: 1200,
      fireRate: 1.4,
      pellets: 1,
      spreadDeg: 0.02,
      recoilPattern: RECOIL_KICK,
      scopeStyle: "optic",
      adsFov: 42,
      onHit: "shock",
      onHitMs: 400,
      fx: fx({
        primary: 0xffd700,
        accent: 0xfff1a8,
        tracer: 0xffe566,
        muzzle: 0xffffff,
        shape: "weird",
        tracerStyle: "beam",
        tracerLife: 0.3,
        kickScale: 1.9,
        fovKickScale: 2.0,
        flashScale: 2.4,
        impactScale: 2.4,
      }),
    }),
};

/** Realistic GLB guns — named after their model files. */
const real = {
  pew: () =>
    gg("real_pew", "PEW", {
      viewmodel: "pew.glb",
      fireStyle: "semi",
      animProfile: "punch",
      sfx: "rifle",
      shellEject: true,
      semiAuto: true,
      damage: 26,
      headshotMultiplier: 2.0,
      magSize: 15,
      reloadMs: 1800,
      fireRate: 5.5,
      pellets: 1,
      spreadDeg: 0.35,
      recoilPattern: RECOIL_MID,
      adsFov: 52,
      fx: fx({
        primary: 0x2c3136,
        accent: 0x1a1c1e,
        tracer: 0xffe08a,
        muzzle: 0xffcc66,
        shape: "pistol",
        tracerStyle: "line",
        tracerLife: 0.08,
        kickScale: 1.05,
        fovKickScale: 0.85,
        flashScale: 0.95,
        impactScale: 1.05,
      }),
    }),
  mac10: () =>
    gg("real_mac10", "MAC-10", {
      viewmodel: "mac10.glb",
      fireStyle: "auto",
      animProfile: "spray",
      sfx: "smg",
      shellEject: true,
      vmKickYaw: 0.55,
      damage: 16,
      headshotMultiplier: 1.65,
      magSize: 30,
      reloadMs: 2100,
      fireRate: 13,
      pellets: 1,
      spreadDeg: 0.95,
      recoilPattern: RECOIL_AUTO,
      adsSpreadMult: 0.55,
      fx: fx({
        primary: 0x3d3d3d,
        accent: 0x1a1a1a,
        tracer: 0xffd27a,
        muzzle: 0xffaa44,
        shape: "smg",
        tracerStyle: "line",
        tracerLife: 0.06,
        kickScale: 0.8,
        fovKickScale: 0.7,
        flashScale: 1.1,
        impactScale: 1.0,
      }),
    }),
  shotgun: () =>
    gg("real_shotgun", "Shotgun", {
      viewmodel: "shotgun.glb",
      fireStyle: "shotgun",
      animProfile: "pump",
      sfx: "shotty",
      semiAuto: true,
      damage: 11,
      headshotMultiplier: 1.25,
      magSize: 6,
      reloadMs: 2800,
      fireRate: 1.15,
      pellets: 8,
      spreadDeg: 2.8,
      recoilPattern: RECOIL_HEAVY,
      maxRange: 45,
      fx: fx({
        primary: 0x5c4033,
        accent: 0x2c2118,
        tracer: 0xffcc88,
        muzzle: 0xffe0a0,
        shape: "shotgun",
        tracerStyle: "dots",
        tracerLife: 0.1,
        kickScale: 2.15,
        fovKickScale: 2.0,
        flashScale: 1.75,
        impactScale: 1.4,
      }),
    }),
  ak47: () =>
    gg("real_ak47", "AK-47", {
      viewmodel: "ak47.glb",
      fireStyle: "auto",
      animProfile: "kick",
      sfx: "rifle",
      shellEject: true,
      damage: 24,
      headshotMultiplier: 1.9,
      magSize: 30,
      reloadMs: 2400,
      fireRate: 10,
      pellets: 1,
      spreadDeg: 0.55,
      recoilPattern: RECOIL_AUTO,
      adsSpreadMult: 0.35,
      adsFov: 50,
      fx: fx({
        primary: 0x3e4a2f,
        accent: 0x2a2a2a,
        tracer: 0xffc56a,
        muzzle: 0xffb040,
        shape: "rifle",
        tracerStyle: "line",
        tracerLife: 0.07,
        kickScale: 1.15,
        fovKickScale: 1.0,
        flashScale: 1.25,
        impactScale: 1.15,
      }),
    }),
  ak47variant: () =>
    gg("real_ak47variant", "AK-47 Variant", {
      viewmodel: "ak47variant.glb",
      fireStyle: "auto",
      animProfile: "kick",
      sfx: "rifle",
      shellEject: true,
      damage: 22,
      headshotMultiplier: 1.85,
      magSize: 30,
      reloadMs: 2300,
      fireRate: 10.5,
      pellets: 1,
      spreadDeg: 0.5,
      recoilPattern: RECOIL_AUTO,
      adsSpreadMult: 0.32,
      adsFov: 50,
      fx: fx({
        primary: 0x4a3520,
        accent: 0x1e1e1e,
        tracer: 0xffd080,
        muzzle: 0xffc060,
        shape: "rifle",
        tracerStyle: "line",
        tracerLife: 0.07,
        kickScale: 1.1,
        fovKickScale: 0.95,
        flashScale: 1.2,
        impactScale: 1.1,
      }),
    }),
  awp: () =>
    gg("real_awp", "AWP", {
      viewmodel: "awp.glb",
      fireStyle: "semi",
      animProfile: "bolt",
      sfx: "sniper",
      shellEject: true,
      semiAuto: true,
      damage: 100,
      headshotMultiplier: 2.5,
      magSize: 5,
      reloadMs: 3200,
      fireRate: 0.55,
      pellets: 1,
      spreadDeg: 0.01,
      recoilPattern: RECOIL_HEAVY,
      scopeStyle: "sniper",
      adsFov: 22,
      adsSensMult: 0.4,
      adsSpreadMult: 0.05,
      fx: fx({
        primary: 0x2c3e50,
        accent: 0x1a252f,
        tracer: 0xffffff,
        muzzle: 0xffe0b0,
        shape: "sniper",
        tracerStyle: "beam",
        tracerLife: 0.26,
        kickScale: 3.2,
        fovKickScale: 3.0,
        flashScale: 1.65,
        impactScale: 1.95,
      }),
    }),
  board: () =>
    gg("real_board", "Board", {
      viewmodel: "board.glb",
      fireStyle: "melee",
      animProfile: "slam",
      sfx: "heavy",
      semiAuto: true,
      damage: 55,
      headshotMultiplier: 1.2,
      magSize: 1,
      reloadMs: 900,
      fireRate: 1.8,
      pellets: 1,
      spreadDeg: 0,
      recoilPattern: RECOIL_HEAVY,
      maxRange: 8,
      meleeCone: 0.38,
      fx: fx({
        primary: 0x8b6914,
        accent: 0x5c4010,
        tracer: 0xd4a574,
        muzzle: 0xffffff,
        shape: "melee",
        tracerStyle: "slash",
        tracerLife: 0.18,
        kickScale: 2.5,
        fovKickScale: 2.2,
        flashScale: 0.15,
        impactScale: 2.2,
      }),
    }),
  rocket: () =>
    gg("real_rocketlaucher", "Rocket Launcher", {
      viewmodel: "rocketlaucher.glb",
      fireStyle: "rocket",
      animProfile: "toss",
      sfx: "rocket",
      semiAuto: true,
      projectile: "rocket",
      explosionRadius: 6.5,
      damage: 90,
      headshotMultiplier: 1,
      magSize: 1,
      reloadMs: 3800,
      fireRate: 0.45,
      pellets: 1,
      spreadDeg: 0.2,
      recoilPattern: RECOIL_HEAVY,
      maxRange: 120,
      adsFov: 55,
      fx: fx({
        primary: 0x556b2f,
        accent: 0x2f2f2f,
        tracer: 0xff6b35,
        muzzle: 0xffaa00,
        shape: "cannon",
        tracerStyle: "thick",
        tracerLife: 0.32,
        kickScale: 2.8,
        fovKickScale: 2.7,
        flashScale: 2.4,
        impactScale: 3.0,
      }),
    }),
  rocketVariant: () =>
    gg("real_rocketlaunchervariant", "Rocket Launcher Variant", {
      viewmodel: "rocketlaunchervariant.glb",
      fireStyle: "rocket",
      animProfile: "toss",
      sfx: "rocket",
      semiAuto: true,
      projectile: "rocket",
      explosionRadius: 7,
      damage: 95,
      headshotMultiplier: 1,
      magSize: 1,
      reloadMs: 4000,
      fireRate: 0.4,
      pellets: 1,
      spreadDeg: 0.15,
      recoilPattern: RECOIL_HEAVY,
      maxRange: 130,
      adsFov: 54,
      fx: fx({
        primary: 0x4a5d23,
        accent: 0x222222,
        tracer: 0xff5520,
        muzzle: 0xff9900,
        shape: "cannon",
        tracerStyle: "thick",
        tracerLife: 0.34,
        kickScale: 3.0,
        fovKickScale: 2.8,
        flashScale: 2.6,
        impactScale: 3.2,
      }),
    }),
  quadRocket: () =>
    gg("real_quadrocket", "Quad Rocket", {
      viewmodel: "quadrocket.glb",
      fireStyle: "rocket",
      animProfile: "toss",
      sfx: "rocket",
      semiAuto: true,
      projectile: "rocket",
      explosionRadius: 5.5,
      damage: 48,
      headshotMultiplier: 1,
      magSize: 4,
      reloadMs: 4500,
      fireRate: 1.2,
      pellets: 1,
      spreadDeg: 0.6,
      recoilPattern: RECOIL_KICK,
      maxRange: 100,
      adsFov: 56,
      fx: fx({
        primary: 0x6b4423,
        accent: 0x333333,
        tracer: 0xff7733,
        muzzle: 0xffbb55,
        shape: "cannon",
        tracerStyle: "thick",
        tracerLife: 0.28,
        kickScale: 2.0,
        fovKickScale: 1.9,
        flashScale: 2.0,
        impactScale: 2.4,
      }),
    }),
};

/**
 * Mixed ladder: original blocky meme guns + named GLB weapons.
 * Final weapon (Golden Banana) still wins the match.
 */
export const GUN_GAME_LADDER: readonly WeaponDef[] = [
  meme.pea(),
  real.pew(),
  meme.chicken(),
  real.mac10(),
  meme.potato(),
  real.shotgun(),
  meme.confetti(),
  real.ak47(),
  meme.bees(),
  real.awp(),
  meme.noodle(),
  real.rocket(),
  meme.slap(),
  real.ak47variant(),
  meme.bubble(),
  real.quadRocket(),
  meme.disco(),
  real.board(),
  meme.spoon(),
  real.rocketVariant(),
  meme.soaker(),
  meme.accordion(),
  meme.shrink(),
  meme.thunder(),
  meme.flappy(),
  meme.hammer(),
  meme.pointer(),
  meme.bananaPeel(),
  meme.ban(),
  meme.golden(),
];

export const GUN_GAME_LENGTH = GUN_GAME_LADDER.length;

export function gunGameWeapon(level: number): WeaponDef {
  const i = Math.max(0, Math.min(GUN_GAME_LENGTH - 1, Math.floor(level)));
  return GUN_GAME_LADDER[i]!;
}

export function gunGameWeaponName(level: number): string {
  return gunGameWeapon(level).name;
}

export function gunGameWeaponById(id: string): WeaponDef | null {
  return GUN_GAME_LADDER.find((w) => w.id === id) ?? null;
}

export function defaultWeaponFx(weapon: WeaponDef): WeaponFx {
  if (weapon.fx) return weapon.fx;
  return {
    primary: 0x2c3136,
    accent: 0x1a1c1e,
    tracer: 0xffe08a,
    muzzle: 0xffcc66,
    shape: "rifle",
    tracerStyle: "line",
    tracerLife: 0.07,
    kickScale: 1,
    fovKickScale: 1,
    flashScale: 1,
    impactScale: 1,
  };
}

/** Fill inferred fire/anim fields onto a weapon copy (for consumers that prefer explicit). */
export function normalizeWeapon(weapon: WeaponDef): WeaponDef {
  return {
    ...weapon,
    fireStyle: resolveFireStyle(weapon),
    animProfile: resolveAnimProfile(weapon),
    burstCount:
      resolveFireStyle(weapon) === "burst"
        ? (weapon.burstCount ?? 3)
        : weapon.burstCount,
  };
}
