import type { WeaponDef, WeaponFx } from "./weapons.js";

/** Classic ladder length — one kill advances you. Final kill with #20 wins. */
export const GUN_GAME_LENGTH = 20;

const RECOIL_SPAM: readonly [number, number][] = [
  [0.15, 0.12],
  [0.18, -0.14],
  [0.2, 0.16],
  [0.22, -0.12],
  [0.24, 0.18],
];

const RECOIL_KICK: readonly [number, number][] = [
  [2.4, 0.3],
  [2.8, -0.4],
  [3.0, 0.2],
];

const RECOIL_HEAVY: readonly [number, number][] = [
  [3.5, 0.5],
  [4.0, -0.6],
];

const RECOIL_MID: readonly [number, number][] = [
  [0.55, 0.1],
  [0.65, -0.15],
  [0.7, 0.12],
  [0.75, -0.1],
  [0.8, 0.18],
];

function fx(partial: WeaponFx): WeaponFx {
  return partial;
}

function gg(
  id: string,
  name: string,
  partial: Omit<
    WeaponDef,
    "id" | "name" | "adsSpreadMult" | "adsFov" | "adsSensMult" | "scopeStyle"
  > &
    Partial<
      Pick<
        WeaponDef,
        | "adsSpreadMult"
        | "adsFov"
        | "adsSensMult"
        | "scopeStyle"
        | "maxRange"
        | "meleeCone"
        | "fx"
      >
    >,
): WeaponDef {
  return {
    id,
    name,
    adsSpreadMult: partial.adsSpreadMult ?? 0.4,
    adsFov: partial.adsFov ?? 58,
    adsSensMult: partial.adsSensMult ?? 0.75,
    scopeStyle: partial.scopeStyle ?? "iron",
    maxRange: partial.maxRange,
    meleeCone: partial.meleeCone,
    fx: partial.fx,
    damage: partial.damage,
    headshotMultiplier: partial.headshotMultiplier,
    magSize: partial.magSize,
    reloadMs: partial.reloadMs,
    fireRate: partial.fireRate,
    pellets: partial.pellets,
    spreadDeg: partial.spreadDeg,
    recoilPattern: partial.recoilPattern,
  };
}

/**
 * 20 ridiculous weapons. Index 0 is the starter; kill with index 19 to win.
 * #6 Tactical Slap / #16 Gravity Hammer use a close cone — not tiny hitscan range.
 */
export const GUN_GAME_LADDER: readonly WeaponDef[] = [
  gg("gg_pea", "Pea Shooter", {
    damage: 9,
    headshotMultiplier: 1.5,
    magSize: 60,
    reloadMs: 1400,
    fireRate: 16,
    pellets: 1,
    spreadDeg: 0.7,
    recoilPattern: RECOIL_SPAM,
    fx: fx({
      primary: 0x3a8f3a,
      accent: 0x76e056,
      tracer: 0x8dff6a,
      muzzle: 0xb6ff88,
      shape: "pistol",
      tracerStyle: "dots",
      tracerLife: 0.09,
      kickScale: 0.45,
      fovKickScale: 0.4,
      flashScale: 0.55,
      impactScale: 0.7,
    }),
  }),
  gg("gg_chicken", "Rubber Chicken", {
    damage: 22,
    headshotMultiplier: 1.25,
    magSize: 12,
    reloadMs: 1800,
    fireRate: 3.2,
    pellets: 1,
    spreadDeg: 1.2,
    recoilPattern: RECOIL_KICK,
    fx: fx({
      primary: 0xe8b84a,
      accent: 0xc45c26,
      tracer: 0xffd27a,
      muzzle: 0xffaa44,
      shape: "weird",
      tracerStyle: "arc",
      tracerLife: 0.14,
      kickScale: 1.4,
      fovKickScale: 1.3,
      flashScale: 1.1,
      impactScale: 1.2,
    }),
  }),
  gg("gg_potato", "Potato Cannon", {
    damage: 58,
    headshotMultiplier: 1.4,
    magSize: 4,
    reloadMs: 2600,
    fireRate: 0.85,
    pellets: 1,
    spreadDeg: 0.35,
    recoilPattern: RECOIL_HEAVY,
    adsFov: 50,
    fx: fx({
      primary: 0x8b6914,
      accent: 0x5c4010,
      tracer: 0xd4a574,
      muzzle: 0xffcc88,
      shape: "cannon",
      tracerStyle: "thick",
      tracerLife: 0.16,
      kickScale: 2.2,
      fovKickScale: 2.4,
      flashScale: 1.8,
      impactScale: 1.8,
    }),
  }),
  gg("gg_confetti", "Confetti SMG", {
    damage: 12,
    headshotMultiplier: 1.6,
    magSize: 40,
    reloadMs: 1900,
    fireRate: 14,
    pellets: 1,
    spreadDeg: 0.55,
    recoilPattern: RECOIL_SPAM,
    fx: fx({
      primary: 0xff4d8d,
      accent: 0x6c5ce7,
      tracer: 0xff9ff3,
      muzzle: 0xffeaa7,
      shape: "smg",
      tracerStyle: "dots",
      tracerLife: 0.08,
      kickScale: 0.55,
      fovKickScale: 0.5,
      flashScale: 0.9,
      impactScale: 0.85,
    }),
  }),
  gg("gg_bees", "Beehive Blaster", {
    damage: 9,
    headshotMultiplier: 1.3,
    magSize: 8,
    reloadMs: 2400,
    fireRate: 1.6,
    pellets: 10,
    spreadDeg: 3.2,
    recoilPattern: RECOIL_KICK,
    fx: fx({
      primary: 0xf0c000,
      accent: 0x2d2d2d,
      tracer: 0xffe066,
      muzzle: 0xfff3bf,
      shape: "shotgun",
      tracerStyle: "dots",
      tracerLife: 0.1,
      kickScale: 1.6,
      fovKickScale: 1.5,
      flashScale: 1.4,
      impactScale: 1.1,
    }),
  }),
  gg("gg_noodle", "Noodle Launcher", {
    damage: 34,
    headshotMultiplier: 1.5,
    magSize: 10,
    reloadMs: 2200,
    fireRate: 2.4,
    pellets: 1,
    spreadDeg: 0.25,
    recoilPattern: RECOIL_MID,
    scopeStyle: "optic",
    adsFov: 48,
    fx: fx({
      primary: 0xe67e22,
      accent: 0xf5cba7,
      tracer: 0xff9f43,
      muzzle: 0xffdab0,
      shape: "cannon",
      tracerStyle: "thick",
      tracerLife: 0.15,
      kickScale: 1.2,
      fovKickScale: 1.1,
      flashScale: 1.2,
      impactScale: 1.3,
    }),
  }),
  gg("gg_slap", "Tactical Slap", {
    damage: 85,
    headshotMultiplier: 1.15,
    magSize: 1,
    reloadMs: 850,
    fireRate: 2,
    pellets: 1,
    spreadDeg: 0,
    recoilPattern: RECOIL_HEAVY,
    maxRange: 9,
    meleeCone: 0.35,
    fx: fx({
      primary: 0xf5d0c5,
      accent: 0xe8a598,
      tracer: 0xffe0d6,
      muzzle: 0xffffff,
      shape: "melee",
      tracerStyle: "arc",
      tracerLife: 0.12,
      kickScale: 2.5,
      fovKickScale: 2.2,
      flashScale: 0.3,
      impactScale: 2,
    }),
  }),
  gg("gg_bubble", "Bubble Blaster", {
    damage: 16,
    headshotMultiplier: 2,
    magSize: 24,
    reloadMs: 2000,
    fireRate: 7,
    pellets: 2,
    spreadDeg: 1.4,
    recoilPattern: RECOIL_MID,
    fx: fx({
      primary: 0x74b9ff,
      accent: 0xa29bfe,
      tracer: 0x81ecec,
      muzzle: 0xdfe6e9,
      shape: "weird",
      tracerStyle: "dots",
      tracerLife: 0.14,
      kickScale: 0.7,
      fovKickScale: 0.6,
      flashScale: 1.1,
      impactScale: 1.4,
    }),
  }),
  gg("gg_disco", "Disco Shotgun", {
    damage: 14,
    headshotMultiplier: 1.4,
    magSize: 6,
    reloadMs: 2500,
    fireRate: 1.5,
    pellets: 8,
    spreadDeg: 2.6,
    recoilPattern: RECOIL_KICK,
    fx: fx({
      primary: 0xfd79a8,
      accent: 0x00cec9,
      tracer: 0xff6bff,
      muzzle: 0xffeaa7,
      shape: "shotgun",
      tracerStyle: "dots",
      tracerLife: 0.11,
      kickScale: 1.8,
      fovKickScale: 1.7,
      flashScale: 1.6,
      impactScale: 1.3,
    }),
  }),
  gg("gg_spoon", "Rail Bent Spoon", {
    damage: 78,
    headshotMultiplier: 2.2,
    magSize: 5,
    reloadMs: 3000,
    fireRate: 0.9,
    pellets: 1,
    spreadDeg: 0.02,
    recoilPattern: RECOIL_HEAVY,
    scopeStyle: "sniper",
    adsFov: 20,
    adsSensMult: 0.4,
    adsSpreadMult: 0,
    fx: fx({
      primary: 0xb2bec3,
      accent: 0x636e72,
      tracer: 0x55efc4,
      muzzle: 0x81ecec,
      shape: "sniper",
      tracerStyle: "beam",
      tracerLife: 0.18,
      kickScale: 2.0,
      fovKickScale: 2.5,
      flashScale: 0.8,
      impactScale: 1.5,
    }),
  }),
  gg("gg_soaker", "Super Soaker", {
    damage: 10,
    headshotMultiplier: 1.3,
    magSize: 80,
    reloadMs: 2800,
    fireRate: 18,
    pellets: 1,
    spreadDeg: 1.0,
    recoilPattern: RECOIL_SPAM,
    fx: fx({
      primary: 0x0984e3,
      accent: 0x74b9ff,
      tracer: 0x4dabf7,
      muzzle: 0xa5d8ff,
      shape: "weird",
      tracerStyle: "thick",
      tracerLife: 0.07,
      kickScale: 0.35,
      fovKickScale: 0.3,
      flashScale: 0.7,
      impactScale: 0.9,
    }),
  }),
  gg("gg_accordion", "Accordion Shotty", {
    damage: 13,
    headshotMultiplier: 1.35,
    magSize: 5,
    reloadMs: 2700,
    fireRate: 1.25,
    pellets: 9,
    spreadDeg: 3.4,
    recoilPattern: RECOIL_HEAVY,
    fx: fx({
      primary: 0xa29bfe,
      accent: 0x6c5ce7,
      tracer: 0xdfe6e9,
      muzzle: 0xffffff,
      shape: "shotgun",
      tracerStyle: "arc",
      tracerLife: 0.12,
      kickScale: 2.0,
      fovKickScale: 1.8,
      flashScale: 1.5,
      impactScale: 1.4,
    }),
  }),
  gg("gg_shrink", "Shrink Ray", {
    damage: 18,
    headshotMultiplier: 2.5,
    magSize: 20,
    reloadMs: 2100,
    fireRate: 5.5,
    pellets: 1,
    spreadDeg: 0.06,
    recoilPattern: RECOIL_MID,
    scopeStyle: "optic",
    adsFov: 40,
    fx: fx({
      primary: 0x00cec9,
      accent: 0x81ecec,
      tracer: 0x55efc4,
      muzzle: 0xb2f7ef,
      shape: "pistol",
      tracerStyle: "beam",
      tracerLife: 0.1,
      kickScale: 0.6,
      fovKickScale: 0.5,
      flashScale: 1.0,
      impactScale: 0.8,
    }),
  }),
  gg("gg_thunder", "Pocket Thunder", {
    damage: 44,
    headshotMultiplier: 1.8,
    magSize: 7,
    reloadMs: 2300,
    fireRate: 2.8,
    pellets: 1,
    spreadDeg: 0.2,
    recoilPattern: RECOIL_KICK,
    fx: fx({
      primary: 0x2d3436,
      accent: 0xfdcb6e,
      tracer: 0xffeaa7,
      muzzle: 0xffffff,
      shape: "pistol",
      tracerStyle: "beam",
      tracerLife: 0.09,
      kickScale: 1.3,
      fovKickScale: 1.4,
      flashScale: 1.7,
      impactScale: 1.6,
    }),
  }),
  gg("gg_flappy", "Flappy Burst", {
    damage: 20,
    headshotMultiplier: 1.7,
    magSize: 3,
    reloadMs: 1600,
    fireRate: 8,
    pellets: 3,
    spreadDeg: 1.1,
    recoilPattern: RECOIL_SPAM,
    fx: fx({
      primary: 0xe17055,
      accent: 0xd63031,
      tracer: 0xff7675,
      muzzle: 0xfab1a0,
      shape: "smg",
      tracerStyle: "dots",
      tracerLife: 0.08,
      kickScale: 0.9,
      fovKickScale: 0.8,
      flashScale: 1.0,
      impactScale: 1.0,
    }),
  }),
  gg("gg_hammer", "Gravity Hammer", {
    damage: 100,
    headshotMultiplier: 1.2,
    magSize: 2,
    reloadMs: 3000,
    fireRate: 0.85,
    pellets: 1,
    spreadDeg: 0,
    recoilPattern: RECOIL_HEAVY,
    maxRange: 11,
    meleeCone: 0.2,
    fx: fx({
      primary: 0x2f3640,
      accent: 0x718093,
      tracer: 0x7f8fa6,
      muzzle: 0xdcdde1,
      shape: "melee",
      tracerStyle: "arc",
      tracerLife: 0.15,
      kickScale: 2.8,
      fovKickScale: 2.6,
      flashScale: 0.4,
      impactScale: 2.4,
    }),
  }),
  gg("gg_pointer", "Laser Pointer of Doom", {
    damage: 48,
    headshotMultiplier: 3,
    magSize: 12,
    reloadMs: 2000,
    fireRate: 3.5,
    pellets: 1,
    spreadDeg: 0,
    recoilPattern: [[1.2, 0]],
    scopeStyle: "optic",
    adsFov: 35,
    adsSensMult: 0.5,
    adsSpreadMult: 0,
    fx: fx({
      primary: 0xc0392b,
      accent: 0x1e272e,
      tracer: 0xff3838,
      muzzle: 0xff6b6b,
      shape: "pistol",
      tracerStyle: "beam",
      tracerLife: 0.2,
      kickScale: 0.5,
      fovKickScale: 0.4,
      flashScale: 0.6,
      impactScale: 1.1,
    }),
  }),
  gg("gg_banana_peel", "Banana Peel SMG", {
    damage: 16,
    headshotMultiplier: 1.6,
    magSize: 45,
    reloadMs: 1700,
    fireRate: 12,
    pellets: 1,
    spreadDeg: 0.45,
    recoilPattern: RECOIL_SPAM,
    fx: fx({
      primary: 0xf1c40f,
      accent: 0xf39c12,
      tracer: 0xffeaa7,
      muzzle: 0xfdf6e3,
      shape: "smg",
      tracerStyle: "line",
      tracerLife: 0.08,
      kickScale: 0.65,
      fovKickScale: 0.55,
      flashScale: 0.95,
      impactScale: 0.95,
    }),
  }),
  gg("gg_ban", "Ban Hammer", {
    damage: 90,
    headshotMultiplier: 1.5,
    magSize: 3,
    reloadMs: 2800,
    fireRate: 1.2,
    pellets: 1,
    spreadDeg: 0,
    recoilPattern: RECOIL_HEAVY,
    maxRange: 10,
    meleeCone: 0.25,
    fx: fx({
      primary: 0x2c3e50,
      accent: 0xe74c3c,
      tracer: 0xff6b6b,
      muzzle: 0xffabab,
      shape: "melee",
      tracerStyle: "arc",
      tracerLife: 0.13,
      kickScale: 2.4,
      fovKickScale: 2.3,
      flashScale: 0.5,
      impactScale: 2.2,
    }),
  }),
  gg("gg_golden", "Golden Banana", {
    damage: 75,
    headshotMultiplier: 2,
    magSize: 1,
    reloadMs: 1400,
    fireRate: 1.5,
    pellets: 1,
    spreadDeg: 0.04,
    recoilPattern: RECOIL_KICK,
    scopeStyle: "optic",
    adsFov: 45,
    fx: fx({
      primary: 0xffd700,
      accent: 0xfff1a8,
      tracer: 0xffe566,
      muzzle: 0xffffff,
      shape: "weird",
      tracerStyle: "beam",
      tracerLife: 0.22,
      kickScale: 1.5,
      fovKickScale: 1.6,
      flashScale: 2.0,
      impactScale: 2.0,
    }),
  }),
];

export function gunGameWeapon(level: number): WeaponDef {
  const i = Math.max(0, Math.min(GUN_GAME_LENGTH - 1, Math.floor(level)));
  return GUN_GAME_LADDER[i]!;
}

export function gunGameWeaponName(level: number): string {
  return gunGameWeapon(level).name;
}

export function gunGameWeaponById(id: string): WeaponDef | null {
  return GUN_GAME_LADDER.find((w) => w.id === id) ?? null;
}


export function defaultWeaponFx(weapon: WeaponDef): WeaponFx {
  if (weapon.fx) return weapon.fx;
  return {
    primary: 0x2c3136,
    accent: 0x1a1c1e,
    tracer: 0xffe08a,
    muzzle: 0xffcc66,
    shape: "rifle",
    tracerStyle: "line",
    tracerLife: 0.07,
    kickScale: 1,
    fovKickScale: 1,
    flashScale: 1,
    impactScale: 1,
  };
}
